quadow/quadow/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.http import HttpResponseRedirect
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_view


def url_redirect(request):
    return HttpResponseRedirect("/login/")


urlpatterns = [
    path('admin/', admin.site.urls),
    # Si la url termina en 'tracker' llamará al fichero urls de la app tracker
    path('tracker/', include("tracker.urls")),
    path('registro/', user_view.registro, name='registro'),
    path('perfil/', user_view.perfil, name='perfil'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html'),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html', next_page='/'), name='logout'),
    path('restablecer-contrasena/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('restablecer-contrasena/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('restablecer-contrasena-confirmado/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('restablecer-contrasena-completado/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('', url_redirect),  # TEMPORAL
]

# Temporal, mientras estemos desarrollando dejaremos el acceso estático de /media de esta manera
# https://docs.djangoproject.com/en/3.0/howto/static-files/#serving-static-files-during-development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quadow/tracker/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import (ListarProyectos, CrearProyecto, EliminarProyecto, EliminarTicket, AbrirTicket, EditarProyecto,
                    ActualizarRoles, EditarTicket)
from . import views

urlpatterns = [
    path('', views.inicio, name="tracker-inicio"),
    path('proyectos/', ListarProyectos.as_view(), name="tracker-proyectos"),
    path('proyectos/nuevo/', CrearProyecto.as_view(), name="crear-proyecto"),
    path('proyectos/<int:pk_proyecto>/cambiar-estado/', views.cambiar_estado_proyecto, name='cambiar-estado-proyecto'),
    # Para acceder a los detalles de un proyecto por su clave primaria (id)
    path('proyectos/<int:pk_proyecto>/', views.retornar_detalle_proyecto, name="detalle-proyecto"),
    path('proyectos/<int:pk>/editar/', EditarProyecto.as_view(), name="editar-proyecto"),
    path('proyectos/<int:pk>/asignar-rol/', ActualizarRoles.as_view(), name="roles-proyecto"),
    path('proyectos/<int:pk>/eliminar/', EliminarProyecto.as_view(), name="eliminar-proyecto"),
    path('proyectos/<int:pk>/abrir-ticket/', AbrirTicket.as_view(), name="abrir-ticket"),
    path('proyectos/<int:pk_proyecto>/ticket/<int:pk_ticket>/', views.retornar_detalle_ticket, name="detalle-ticket"),
    path('proyectos/<int:pk_proyecto>/ticket/<int:pk>/eliminar/', EliminarTicket.as_view(), name="eliminar-ticket"),
    path('proyectos/<int:pk_proyecto>/ticket/<int:pk>/editar/', EditarTicket.as_view(), name="editar-ticket"),
    path('proyectos/<int:pk_proyecto>/ticket/<int:pk>/cambiar-estado/<int:estado>/', views.cambiar_estado_ticket,
         name="cambiar-estado"),
]

quadow/tracker/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User  # Importamos los usuarios de django
from django.urls import reverse
from PIL import Image

ESTADO_PROYECTO = (
    ("ACTIVO", "Activo"),
    ("FINALIZADO", "Finalizado"),
)

PRIORIDAD_TICKET = (
    (0, "Urgente"),
    (1, "Alta"),
    (2, "Media"),
    (3, "Baja"),
)

# https://support.euphoria.co.za/support/solutions/articles/60399-what-do-the-ticket-statuses-mean-
ESTADO_TICKET = (
    (0, "Abierto"),  # El usuario ha abierto el ticket y aún no ha sido procesado
    (1, "Pendiente"),  # El ticket está siendo procesado
    (2, "Resuelto"),  # El ticket ha sido resuelto
    (3, "Cerrado"),  # El ticket ha sido cerrado, generalmente ha sido aceptado por el usuario
)

TIPO_TICKET = (
    ("BUG", "Bug"),
    ("CONSULTA", "Consulta"),
    ("FEATURE REQUEST", "Solicitud de función"),
    ("OTROS", "Otros"),
)

ROL_EMPLEADO = (
    ("ADMIN", "Admin"),
    ("DEVELOPER", "Developer"),
    ("PROJECT MANAGER", "Project Manager"),
    ("BETA TESTER", "Beta Tester"),
    ("NS/NC", "NS/NC"),
)

TAMANO_MAX = 512


class Proyecto(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()
    fecha_creacion = models.DateTimeField(default=timezone.now)
    usuario_creador = models.ForeignKey(User, on_delete=models.CASCADE)
    estado = models.CharField(max_length=10, choices=ESTADO_PROYECTO, default="ACTIVO")
    imagen = models.ImageField(default='interr.jpg', upload_to='imagenes_proyectos')

    def __str__(self):
        return self.nombre

    '''def save(self, **kwargs):
        super().save()

        img = Image.open(self.imagen.path)

        if img.height > TAMANO_MAX or img.width > TAMANO_MAX:
            tamano_salida = (TAMANO_MAX, TAMANO_MAX)
            img.thumbnail(tamano_salida)
            img.save(self.imagen.path, quality=80)'''

    def get_absolute_url(self):
        return reverse('detalle-proyecto', kwargs={'pk_proyecto': self.pk})

    class Meta:
        ordering = ['fecha_creacion', '-estado']


class RolesProyecto(models.Model):
    proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=15, choices=ROL_EMPLEADO, default="NS/NC")

    def __str__(self):
        return f'{self.proyecto} - {self.usuario} - {self.tipo}'

    def get_absolute_url(self):
        return reverse('detalle-proyecto', kwargs={'pk_proyecto': self.proyecto.pk})


class Ticket(models.Model):
    titulo = models.CharField(max_length=50)
    descripcion = models.TextField()
    usuario_creador = models.ForeignKey(User, on_delete=models.CASCADE)
    prioridad = models.IntegerField(choices=PRIORIDAD_TICKET, default=3)
    estado = models.IntegerField(choices=ESTADO_TICKET, default=0)
    fecha_creacion = models.DateTimeField(default=timezone.now)
    proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=15, choices=TIPO_TICKET, default="OTROS")

    def __str__(self):
        return self.titulo

    # Para ordenar los tickets primero por prioridad y después por estado
    class Meta:
        ordering = ['estado', 'prioridad']

    def get_absolute_url(self):
        return reverse('detalle-ticket', kwargs={'pk_proyecto': self.proyecto.pk, 'pk_ticket': self.pk})


class ComentariosTicket(models.Model):
    texto = models.TextField()
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'Comentario {self.autor} #{self.id}'


class AdjuntosTicket(models.Model):
    fichero = models.FileField(upload_to='adjuntos')
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    fecha_subida = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.ticket} - {self.autor} - {self.fichero.name}'

quadow/tracker/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView, CreateView, UpdateView
from django.contrib import messages

from .formulario import FormularioActualizarImagenProyecto, FormularioSubirAdjunto, FormularioComentarTicket
from .models import Proyecto, Ticket, ComentariosTicket, RolesProyecto, AdjuntosTicket

import datetime


def mensaje_error(request):
    messages.error(request, f'Ha ocurrido un error. Por favor, revise los datos.')


# Vista para ir al inicio
@login_required
def inicio(request):
    # Gráfico de tarta
    labels_roles = ['ADMIN', 'DEVELOPER', 'PROJECT MANAGER', 'BETA TESTER', 'NS/NC']
    data_roles = []

    for i in range(len(labels_roles)):
        data_roles.append(Proyecto.objects.filter(
            Q(rolesproyecto__in=RolesProyecto.objects.filter(usuario=request.user, tipo=labels_roles[i]))).count())

    # Gráfico de área
    data_tickets = []
    anyo_actual = datetime.datetime.now().year
    proyectos_del_usuario = RolesProyecto.objects.filter(usuario=request.user).values_list('proyecto').distinct()

    for i in range(12):
        data_tickets.append(Ticket.objects.filter(Q(fecha_creacion__year=anyo_actual),
                                                  Q(fecha_creacion__month=i + 1),
                                                  Q(proyecto_id__in=proyectos_del_usuario)).count())

    # Tipo de tickets
    tipo_tickets = []
    from .models import TIPO_TICKET
    for i in range(len(TIPO_TICKET)):
        tipo_tickets.append(Ticket.objects.filter(Q(tipo=TIPO_TICKET[i][0]),
                                                  Q(proyecto_id__in=proyectos_del_usuario)).count())

    numero_tickets_usuario = sum(tipo_tickets)
    for i in range(len(tipo_tickets)):
        tipo_tickets[i] = round((tipo_tickets[i] * 100) / numero_tickets_usuario) if numero_tickets_usuario > 0 else 0

    # Porcentaje proyectos finalizados
    numero_roles_del_usuario = RolesProyecto.objects.filter(usuario=request.user).distinct('proyecto').all().count()
    proyectos_finalizados_porcentaje = round((Proyecto.objects.filter(usuario_creador=request.user,
                                                                      estado="FINALIZADO").all().count() * 100) /
                                             numero_roles_del_usuario) if numero_roles_del_usuario > 0 else 0

    contexto = {
        'titulo': 'Dashboard',
        'labels_roles': labels_roles,
        'data_roles': data_roles,
        'data_tickets': data_tickets,
        'proyectos': Proyecto.objects.all(),
        'proyectos_asignados': RolesProyecto.objects.filter(usuario=request.user).distinct('proyecto').all(),
        'tipo_tickets': tipo_tickets,
        'roles_asignados': RolesProyecto.objects.filter(usuario=request.user).all().count(),
        'proyectos_finalizados_porcentaje': proyectos_finalizados_porcentaje
    }
    return render(request, 'tracker/index.html', contexto)


# Vista para ver los proyectos
@login_required
def retornar_proyectos(request):
    contexto = {
        # Le pasamos todos los objetos de la tabla Proyecto de la base de datos ordenados por fecha
        'proyectos': Proyecto.objects.all().order_by("fecha_creacion"),
        'titulo': "Proyectos"
    }
    return render(request, "tracker/lista-proyectos.html", contexto)


class ListarProyectos(LoginRequiredMixin, ListView):
    model = Proyecto
    template_name = "tracker/lista-proyectos.html"
    context_object_name = 'proyectos'
    extra_context = {'titulo': 'Proyectos'}

    # Solo devuelve los proyectos donde estemos como personal autorizado, hayamos creado o seamos superusuario django
    def get_queryset(self):
        filtro = RolesProyecto.objects.filter(usuario=self.request.user)
        return Proyecto.objects.filter(
            Q(rolesproyecto__in=filtro)).distinct() if not self.request.user.is_superuser else self.model.objects.all()


class CrearProyecto(LoginRequiredMixin, CreateView):
    model = Proyecto
    fields = ['nombre', 'descripcion', 'imagen']
    template_name = "tracker/crear-proyecto.html"
    extra_context = {'titulo': 'Nuevo proyecto'}

    def form_valid(self, form):
        form.instance.usuario_creador = self.request.user
        messages.success(self.request, f'Proyecto creado.')
        return super().form_valid(form)

    def form_invalid(self, form):
        mensaje_error(self.request)
        return super().form_invalid(form)


class EditarProyecto(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Proyecto
    fields = ['nombre', 'descripcion', 'imagen']
    template_name = "tracker/editar-proyecto.html"
    extra_context = {'titulo': 'Editar proyecto'}

    def test_func(self):
        proyecto = Proyecto.objects.filter(id=self.kwargs.get('pk')).first()
        filtro_por_tipo = RolesProyecto.objects.filter(usuario=self.request.user, proyecto=proyecto)
        return True if filtro_por_tipo.filter(
            Q(tipo='PROJECT MANAGER') | Q(tipo='ADMIN')) or self.request.user.is_superuser else False


class ActualizarRoles(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = RolesProyecto
    fields = ['usuario', 'tipo']
    template_name = "tracker/asignar-rol.html"
    extra_context = {'titulo': 'Actualizar proyecto'}

    def form_valid(self, form):
        form.instance.proyecto_id = self.kwargs.get('pk')
        messages.success(self.request, f'Rol añadido al proyecto.')
        return super().form_valid(form)

    def form_invalid(self, form):
        mensaje_error(self.request)
        return super().form_invalid(form)

    def test_func(self):
        proyecto = Proyecto.objects.filter(id=self.kwargs.get('pk')).first()
        filtro_por_tipo = RolesProyecto.objects.filter(usuario=self.request.user, proyecto=proyecto)
        return True if filtro_por_tipo.filter(
            Q(tipo='PROJECT MANAGER') | Q(tipo='ADMIN')) or self.request.user.is_superuser else False


# Vista para ver los detalles de un proyecto
@login_required
def retornar_detalle_proyecto(request, pk_proyecto):
    objeto = get_object_or_404(Proyecto, pk=pk_proyecto)
    filtro_por_tipo = RolesProyecto.objects.filter(usuario=request.user, proyecto=pk_proyecto)

    if request.method == 'POST':
        if filtro_por_tipo.filter(tipo='ADMIN') or filtro_por_tipo.filter(
                tipo='PROJECT MANAGER') or request.user.is_superuser:
            if 'cambiar_imagen' in request.POST:
                formulario_imagen = FormularioActualizarImagenProyecto(request.POST, request.FILES, instance=objeto)
                if formulario_imagen.is_valid():
                    formulario_imagen.save()
                    messages.success(request, f'Imagen actualizada.')
                    return redirect('detalle-proyecto', pk_proyecto)
                else:
                    mensaje_error(request)
                    return redirect('detalle-proyecto', pk_proyecto)
            elif 'eliminar_rol' in request.POST:
                rol_eliminar = request.POST.get('eliminar_rol')
                if rol_eliminar and filtro_por_tipo.filter(tipo='ADMIN') or filtro_por_tipo.filter(
                        tipo='PROJECT MANAGER') or request.user.is_superuser:
                    RolesProyecto.objects.filter(id=rol_eliminar).delete()
                    messages.success(request, f'Rol eliminado.')
                    return redirect('detalle-proyecto', pk_proyecto) if RolesProyecto.objects.filter(usuario=request.user, proyecto=pk_proyecto) else redirect('tracker-proyectos')
                else:
                    mensaje_error(request)
                    return redirect('detalle-proyecto', pk_proyecto)
        else:
            mensaje_error(request)
            return redirect('detalle-proyecto', pk_proyecto)
    else:
        # Controlamos que solo pueda acceder al proyecto aquel que está como personal asignado
        if filtro_por_tipo or request.user.is_superuser:
            contexto = {
                'proyecto': objeto,
                'titulo': objeto.nombre + " - Detalles Proyecto",
                # Le pasamos todos los tickets que coincidan con la PK del proyecto
                'tickets': Ticket.objects.filter(proyecto=pk_proyecto),
                'roles': RolesProyecto.objects.filter(proyecto=pk_proyecto),
                'admins': RolesProyecto.objects.filter(proyecto=pk_proyecto, tipo='ADMIN', usuario=request.user),
                'proyect_managers': RolesProyecto.objects.filter(proyecto=pk_proyecto, tipo='PROJECT MANAGER',
                                                                 usuario=request.user)
            }
            return render(request, 'tracker/detalle-proyecto.html', contexto)
        else:
            raise Http404("No existe el proyecto.")


class AbrirTicket(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Ticket
    fields = ['titulo', 'descripcion', 'prioridad', 'tipo']
    template_name = "tracker/abrir-ticket.html"
    extra_context = {'titulo': 'Abrir ticket'}

    def form_valid(self, form):
        form.instance.usuario_creador = self.request.user
        form.instance.proyecto_id = self.kwargs.get('pk')
        messages.success(self.request, f'Ticket abierto.')
        return super().form_valid(form)

    def form_invalid(self, form):
        mensaje_error(self.request)
        return super().form_invalid(form)

    # Solo quien esté en la lista de personal asignado podrá crear tickets
    def test_func(self):
        proyecto = Proyecto.objects.filter(id=self.kwargs.get('pk')).first()
        filtro_por_tipo = RolesProyecto.objects.filter(usuario=self.request.user, proyecto=proyecto)

quadow/tracker/templates/tracker/abrir-ticket.html
{% extends "tracker/base.html" %}
{% load static %}

{% block content %}
    <div class="container-fluid">
        <h3 class="text-dark mb-4">Abrir ticket</h3>
        <div class="row mb-3">
            <div class="col-lg-12">
                <div class="row mb-3 d-none">
                    <div class="col">
                        <div class="card text-white bg-primary shadow">
                            <div class="card-body">
                                <div class="row mb-2">
                                    <div class="col">
                                        <p class="m-0">Peformance</p>
                                        <p class="m-0"><strong>65.2%</strong></p>
                                    </div>
                                    <div class="col-auto"><i class="fas fa-rocket fa-2x"></i></div>
                                </div>
                                <p class="text-white-50 small m-0"><i class="fas fa-arrow-up"></i>&nbsp;5% since last
                                    month</p>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card text-white bg-success shadow">
                            <div class="card-body">
                                <div class="row mb-2">
                                    <div class="col">
                                        <p class="m-0">Peformance</p>
                                        <p class="m-0"><strong>65.2%</strong></p>
                                    </div>
                                    <div class="col-auto"><i class="fas fa-rocket fa-2x"></i></div>
                                </div>
                                <p class="text-white-50 small m-0"><i class="fas fa-arrow-up"></i>&nbsp;5% since last
                                    month</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="card shadow mb-3">
                            <div class="card-header py-3">
                                <p class="text-primary m-0 font-weight-bold">Detalles</p>
                            </div>
                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col">
                                            <div class="form-group"><label
                                                    for="username"><strong>Título</strong></label><input
                                                    class="form-control" type="text"
                                                    name="titulo"></div>
                                        </div>
                                        <div class="col">
                                            <div class="form-group"><label
                                                    for="email"><strong>Prioridad</strong></label><select
                                                    class="form-control" name="prioridad">
                                                {% for prioridad in  form.prioridad %}
                                                    {{ prioridad }}
                                                {% endfor %}
                                            </select></div>
                                        </div>
                                        <div class="col">
                                            <div class="form-group"><label
                                                    for="email"><strong>Tipo</strong></label><select
                                                    class="form-control" name="tipo">
                                                {% for tipo in  form.tipo %}
                                                    {{ tipo }}
                                                {% endfor %}
                                            </select></div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col">
                                            <div class="form-group"><label
                                                    for="descripcion"><strong>Descripción</strong><br></label><textarea
                                                    class="form-control" name="descripcion"></textarea></div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-primary btn-sm" type="submit">Enviar</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

quadow/tracker/templates/tracker/asignar-rol.html
{% extends "tracker/base.html" %}
{% load static %}

{% block content %}
    <div class="container-fluid">
        <h3 class="text-dark mb-4">Asignar rol al proyecto #{{ view.kwargs.pk }}</h3>
        <form method="POST">
            {% csrf_token %}
            <div class="row mb-3">
                <div class="col">
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="text-primary font-weight-bold m-0">Usuarios</h6>
                        </div>
                        <div class="card-body"><select class="custom-select" name="usuario"
                                                       size="10">
                            {% for usuario in  form.usuario %}
                                {% if not forloop.first %}
                                    {{ usuario }}
                                {% endif %}
                            {% endfor %}
                        </select></div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="text-primary font-weight-bold m-0">Tipo</h6>
                        </div>
                        <div class="card-body"><select class="custom-select" name="tipo"
                                                       size="10">
                            {% for tipo in  form.tipo %}
                                {{ tipo }}
                            {% endfor %}
                        </select></div>
                    </div>
                </div>
            </div>
            <button class="btn btn-primary btn-sm" type="submit">Enviar</button>
        </form>
    </div>
{% endblock %}

quadow/tracker/templates/tracker/crear-proyecto.html
{% extends "tracker/base.html" %}
{% load static %}

{% block content %}
    <div class="container-fluid">
        <h3 class="text-dark mb-4">Nuevo proyecto</h3>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row mb-3">
                <div class="col-lg-4">
                    <div class="card mb-3">
                        <div class="card-body text-center shadow"><img class="rounded-circle mb-3 mt-4" id="imagen_auto"
                                                                       src="{% static 'assets/img/interr.jpg' %}"
                                                                       width="160"
                                                                       height="160">
                            <div class="mb-3">
                                <div class="custom-file">
                                    <input type="file" accept="image/*" class="custom-file-input" name="imagen"
                                           id="id_imagen" onchange="cambiarImagen(event)">
                                    <label class="custom-file-label" for="customFile">Elegir imagen</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="row">
                        <div class="col">
                            <div class="card shadow mb-3">
                                <div class="card-header py-3">
                                    <p class="text-primary m-0 font-weight-bold">Detalles</p>
                                </div>
                                <div class="card-body">
                                    <div class="form-row">
                                        <div class="col">
                                            <div class="form-group"><label
                                                    for="nombre"><strong>Nombre</strong></label><input
                                                    class="form-control" type="text"
                                                    name="nombre" maxlength="50" required></div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col">
                                            <div class="form-group"><label
                                                    for="descripcion"><strong>Descripción</strong><br></label><textarea
                                                    class="form-control" name="descripcion" required></textarea></div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-primary btn-sm" type="submit">Enviar</button>
                                    </div>

                                </div>
                            </div>
                            <small class="form-text text-muted">Los usuarios, junto a sus roles, podrán ser asignados
                                una
                                vez creado el proyecto.</small></div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

quadow/tracker/templates/tracker/editar-proyecto.html
{% extends "tracker/base.html" %}
{% load static %}

{% block content %}
    <div class="container-fluid">
        <h3 class="text-dark mb-4">Editar proyecto #{{ object.id }}</h3>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row mb-3">
                <div class="col-lg-4">
                    <div class="card mb-3">
                        <div class="card-body text-center shadow"><img class="rounded-circle mb-3 mt-4" id="imagen_auto"
                                                                       src="{{ object.imagen.url }}"
                                                                       width="160"
                                                                       height="160">
                            <div class="mb-3">
                                <div class="custom-file">
                                    <input type="file" accept="image/*" class="custom-file-input" name="imagen"
                                           id="id_imagen" onchange="cambiarImagen(event)">
                                    <label class="custom-file-label" for="customFile">Elegir imagen</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="row">
                        <div class="col">
                            <div class="card shadow mb-3">
                                <div class="card-header py-3">
                                    <p class="text-primary m-0 font-weight-bold">Detalles</p>
                                </div>
                                <div class="card-body">
                                    <div class="form-row">
                                        <div class="col">
                                            <div class="form-group"><label
                                                    for="nombre"><strong>Nombre</strong></label><input
                                                    class="form-control" type="text"
                                                    name="nombre" value="{{ object.nombre }}"></div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col">
                                            <div class="form-group"><label
                                                    for="descripcion"><strong>Descripción</strong><br></label><textarea
                                                    class="form-control"
                                                    name="descripcion">{{ object.descripcion }}</textarea></div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-primary btn-sm" type="submit">Enviar</button>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}